#language to use in tavis containers
language: python
python:
    - "3.6.7"
install:
  - pip install -r Requirements.txt
# command to run tests
script:
  - python -m pytest --cov

sudo: required

after_success: 
- coveralls
